<html>
    <body>
        <p>Jobs for today:
            <?php
            echo "<br>";
            foreach ($tasks as $task) {
            echo $task['task'] . '<form action="completedTask" method="POST">
            <input type="submit" name="completedButton" value="Completed">
            <input type="hidden" name="taskId\" value= ' . $task['id'] . '>
            </form><br>';
            };
            ?></p>
    </body>

    <form action="/addTask" method="POST">
        <input type="text" name="task">
        <input type="submit">
    </form>
</html>