<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
                <nav class="navbar navbar-dark bg-primary">
                    <span class="navbar-brand mb-0 h1">PHP SLIM - To Do List</span>
                </nav>
        </div>
        <div class="row">
            <div class="col-xs-offset-1 col-xs-10">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Task</th>
                            <th scope="col">Completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $listsWithTasks = [];
                        foreach($tasks as $task) {
                            array_push($listsWithTasks, $task["to_do_list_id"]);
                        }
                        foreach ($lists as $list) {
                            if (in_array($list['id'], $listsWithTasks)){
                            echo '<tr class="bg-primary"><td colspan="3">' . $list['to_do_list'] . '</td></tr>';
                            foreach($tasks as $task) {
                                if($list['id'] == $task['to_do_list_id']) {
                                    echo '<tr><th scope="row">' . $task['id'] . '</th><td>' . $task['task'] .'</td>' .
                                        '<td><form action="completedTask" method="POST">
<input class="btn btn-success" type="submit" name="completedButton" value="Completed">
                        <input type="hidden" name="taskId" value= ' . $task['id'] . '>
                        </form></td></tr>';
                                }
                            }
                          };
                        }
                        ?>
                        </tr>
                    </tbody>
                </table>
                <p>Add Task</p>
                <form action="/addTask" method="POST" class="form-inline">
                    <select name="listId">
                    <?php
                    foreach ($lists as $list) {
                        echo '<option  value= ' . $list['id'] . '>' . $list['to_do_list'] . '</option>';
                    };
                    ?>
                    </select>
                    <input class="form-control mr-sm-2" type="text" name="task">
                    <input class="btn btn-success" type="submit" value="Submit">
                </form>
                <p>Add To Do List</p>
                <form action="/addToDoList" method="POST" class="form-inline">
                    <input class="form-control mr-sm-4" type="text" name="toDolist">
                    <input class="btn btn-success" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
</body>
</html>